### ISSUE TITLE
Slight structural changes

### ISSUE THREAD

**Issue by projectgoav** [Sheepzez/Matrixonator-Java#15]
I propose that we move the ERO methods from RREF matrix back into the standard Matrix class. I think these are standard operations we can do on all matrices.
I also propose thet stepOne, Two & Three should become hidden within the RREF class and such the test should be removed (as they would be private) and so the creation of the RREF Matrix tests would cover handling these methods. 
I also suggest that we remove the parent object from a RREF Matrix. Why is this needed? Surely we can just reference this to the bas Matrix class underneath?

**Comment by Sheepzez** [comment]
Looks to be a decent proposal to me. If we're keeping the ERO methods public, you should leave in the unit tests for them in 5c05ae325389edad92f43ffe1dc63deddcae149a. 
What's the purpose of making stepOne/Two/Three private? It's unfortunate to lose the test cases for them, since we may refactor in the future and that gives us a much better indication of what went wrong when refactoring.
The instance variable in RREFMatrix is there to keep track of which regular Matrix the RREFMatrix belongs to. How else do you propose to keep track of this?

**Comment by projectgoav** [comment]
I agree with the ERO bits. I suppose it would be better for the step methods to remain public for testing, but perhaps hide them later when deploying (when we get to that?) Surely there will be a way of doing that before build!

As for keeping track of the RREF. Currently, when one is created the name of the parent is prefixed with "RREF". Therefore, keeping track of the parent just requires removal of "RREF" and thus you have the parent?

**Comment by Sheepzez** [comment]
Matrix names are not unique though, so you wouldn't know which matrix it
will get. There also isn't a method for searching for a matrix by name,
since not all matrices will necessarily be in the list of matrices down the
left side if the GUI.

**Comment by projectgoav** [comment]
Hmm, that'll make a big memory footprint with objects all linked to each other... I'll have a think about that one!

**Comment by Sheepzez** [comment]
They're only pointers, so its like 32 bits. If I remember my pointer size
correctly...
